version: '3.7'

services:
    mongodb:
        image: mongo:latest
        container_name: mongodb
        restart: always
        environment:
            MONGO_INITDB_DATABASE: db-vote
        ports:
            - 27017:27017
        volumes:
            - .docker/database:/data/db
    
    rabbitmq:
        image: 'rabbitmq:3.8-management-alpine'
        container_name: rabbitmq
        hostname: rabbitmq
        ports:
            - '15672:15672'
            - '5672:5672'
        volumes:
            - '.docker/.rabbitmq_data:/var/lib/rabbitmq/mnesia'
        environment:
            - RABBITMQ_DEFAULT_USER=admin
            - RABBITMQ_DEFAULT_PASS=admin
